apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myappspa
  namespace: myapp
  labels:
    app: myappspa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
    - host: 52.164.190.43.xip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: myappspa
              servicePort: 8080
